AVIUM_BUILDTYPE := Unoffical
AVIUM_VERSION_APPEND_TIME_OF_DAY := false

# GMS
WITH_GMS := false
TARGET_GMS_TYPE := FULL

# Google IMS
TARGET_INCLUDE_GOOGLEIME := true
TARGET_GOOGLEIME_OVERRIDE_IME := true

AVIUM_MAINTAINER := 觉得不能
